services:
  - type: web
    name: bevco-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
    plan: free
    pythonVersion: 3.11
